# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PasswordVault (iOS)' do
  use_frameworks!
  pod 'BCrypt'
end

target 'PasswordVault (macOS)' do
  use_frameworks!
  pod 'BCrypt'
end
